#!/usr/bin/env bash
set -euo pipefail
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

# sleep fgru density_gau seed=0
/home/ec2-user/EventDetectionPDF/.venv/bin/python train.py --dataset sleep --model fgru --objective density_gau --datadir data/sleep --epochs 20 --folds 4 --bs 32 --downsample 10 --agg_feats stat --use_cat True --normalize True --workers 4 --seed 0 --density_prior sparse --best_metric mAP --save_all_epochs False --lr 0.003 --weight_decay 0.0 --clip_grad_norm 0.1 --tune_cutoff_steps 11 --tune_smooth_values none,1,10,100,1000 --tune_alternating True --score_after_train False --eval_every 5 --wandb True --wandb_project event-detection-pdf --wandb_log_artifacts True --tolerance_scale 1.0 --wandb_group P10-online-smoothing-train-only --wandb_tags paper-density-likelihood-rewrite,sleep,P10,online-smoothing,train-only --run_tag online_smoothing_e20_bs32_eval5 --device cuda

# sleep fgru density_custom seed=0
/home/ec2-user/EventDetectionPDF/.venv/bin/python train.py --dataset sleep --model fgru --objective density_custom --datadir data/sleep --epochs 20 --folds 4 --bs 32 --downsample 10 --agg_feats stat --use_cat True --normalize True --workers 4 --seed 0 --density_prior sparse --best_metric mAP --save_all_epochs False --lr 0.003 --weight_decay 0.0 --clip_grad_norm 0.1 --tune_cutoff_steps 11 --tune_smooth_values none,1,10,100,1000 --tune_alternating True --score_after_train False --eval_every 5 --wandb True --wandb_project event-detection-pdf --wandb_log_artifacts True --tolerance_scale 1.0 --wandb_group P10-online-smoothing-train-only --wandb_tags paper-density-likelihood-rewrite,sleep,P10,online-smoothing,train-only --run_tag online_smoothing_e20_bs32_eval5 --device cuda

# sleep fgru seg seed=0
/home/ec2-user/EventDetectionPDF/.venv/bin/python train.py --dataset sleep --model fgru --objective seg --datadir data/sleep --epochs 20 --folds 4 --bs 32 --downsample 10 --agg_feats stat --use_cat True --normalize True --workers 4 --seed 0 --density_prior sparse --best_metric mAP --save_all_epochs False --lr 0.003 --weight_decay 0.0 --clip_grad_norm 0.1 --tune_cutoff_steps 11 --tune_smooth_values none,1,10,100,1000 --tune_alternating True --score_after_train False --eval_every 5 --wandb True --wandb_project event-detection-pdf --wandb_log_artifacts True --tolerance_scale 1.0 --wandb_group P10-online-smoothing-train-only --wandb_tags paper-density-likelihood-rewrite,sleep,P10,online-smoothing,train-only --run_tag online_smoothing_e20_bs32_eval5 --device cuda

# sleep flstm density_gau seed=0
/home/ec2-user/EventDetectionPDF/.venv/bin/python train.py --dataset sleep --model flstm --objective density_gau --datadir data/sleep --epochs 20 --folds 4 --bs 32 --downsample 10 --agg_feats stat --use_cat True --normalize True --workers 4 --seed 0 --density_prior sparse --best_metric mAP --save_all_epochs False --lr 0.003 --weight_decay 0.0 --clip_grad_norm 0.1 --tune_cutoff_steps 11 --tune_smooth_values none,1,10,100,1000 --tune_alternating True --score_after_train False --eval_every 5 --wandb True --wandb_project event-detection-pdf --wandb_log_artifacts True --tolerance_scale 1.0 --wandb_group P10-online-smoothing-train-only --wandb_tags paper-density-likelihood-rewrite,sleep,P10,online-smoothing,train-only --run_tag online_smoothing_e20_bs32_eval5 --device cuda

# sleep flstm density_custom seed=0
/home/ec2-user/EventDetectionPDF/.venv/bin/python train.py --dataset sleep --model flstm --objective density_custom --datadir data/sleep --epochs 20 --folds 4 --bs 32 --downsample 10 --agg_feats stat --use_cat True --normalize True --workers 4 --seed 0 --density_prior sparse --best_metric mAP --save_all_epochs False --lr 0.003 --weight_decay 0.0 --clip_grad_norm 0.1 --tune_cutoff_steps 11 --tune_smooth_values none,1,10,100,1000 --tune_alternating True --score_after_train False --eval_every 5 --wandb True --wandb_project event-detection-pdf --wandb_log_artifacts True --tolerance_scale 1.0 --wandb_group P10-online-smoothing-train-only --wandb_tags paper-density-likelihood-rewrite,sleep,P10,online-smoothing,train-only --run_tag online_smoothing_e20_bs32_eval5 --device cuda

# sleep flstm seg seed=0
/home/ec2-user/EventDetectionPDF/.venv/bin/python train.py --dataset sleep --model flstm --objective seg --datadir data/sleep --epochs 20 --folds 4 --bs 32 --downsample 10 --agg_feats stat --use_cat True --normalize True --workers 4 --seed 0 --density_prior sparse --best_metric mAP --save_all_epochs False --lr 0.003 --weight_decay 0.0 --clip_grad_norm 0.1 --tune_cutoff_steps 11 --tune_smooth_values none,1,10,100,1000 --tune_alternating True --score_after_train False --eval_every 5 --wandb True --wandb_project event-detection-pdf --wandb_log_artifacts True --tolerance_scale 1.0 --wandb_group P10-online-smoothing-train-only --wandb_tags paper-density-likelihood-rewrite,sleep,P10,online-smoothing,train-only --run_tag online_smoothing_e20_bs32_eval5 --device cuda

# sleep causal_transformer density_gau seed=0
/home/ec2-user/EventDetectionPDF/.venv/bin/python train.py --dataset sleep --model causal_transformer --objective density_gau --datadir data/sleep --epochs 20 --folds 4 --bs 32 --downsample 10 --agg_feats stat --use_cat True --normalize True --workers 4 --seed 0 --density_prior sparse --best_metric mAP --save_all_epochs False --lr 0.003 --weight_decay 0.0 --clip_grad_norm 0.1 --tune_cutoff_steps 11 --tune_smooth_values none,1,10,100,1000 --tune_alternating True --score_after_train False --eval_every 5 --wandb True --wandb_project event-detection-pdf --wandb_log_artifacts True --tolerance_scale 1.0 --wandb_group P10-online-smoothing-train-only --wandb_tags paper-density-likelihood-rewrite,sleep,P10,online-smoothing,train-only --run_tag online_smoothing_e20_bs32_eval5 --device cuda

# sleep causal_transformer density_custom seed=0
/home/ec2-user/EventDetectionPDF/.venv/bin/python train.py --dataset sleep --model causal_transformer --objective density_custom --datadir data/sleep --epochs 20 --folds 4 --bs 32 --downsample 10 --agg_feats stat --use_cat True --normalize True --workers 4 --seed 0 --density_prior sparse --best_metric mAP --save_all_epochs False --lr 0.003 --weight_decay 0.0 --clip_grad_norm 0.1 --tune_cutoff_steps 11 --tune_smooth_values none,1,10,100,1000 --tune_alternating True --score_after_train False --eval_every 5 --wandb True --wandb_project event-detection-pdf --wandb_log_artifacts True --tolerance_scale 1.0 --wandb_group P10-online-smoothing-train-only --wandb_tags paper-density-likelihood-rewrite,sleep,P10,online-smoothing,train-only --run_tag online_smoothing_e20_bs32_eval5 --device cuda

# sleep causal_transformer seg seed=0
/home/ec2-user/EventDetectionPDF/.venv/bin/python train.py --dataset sleep --model causal_transformer --objective seg --datadir data/sleep --epochs 20 --folds 4 --bs 32 --downsample 10 --agg_feats stat --use_cat True --normalize True --workers 4 --seed 0 --density_prior sparse --best_metric mAP --save_all_epochs False --lr 0.003 --weight_decay 0.0 --clip_grad_norm 0.1 --tune_cutoff_steps 11 --tune_smooth_values none,1,10,100,1000 --tune_alternating True --score_after_train False --eval_every 5 --wandb True --wandb_project event-detection-pdf --wandb_log_artifacts True --tolerance_scale 1.0 --wandb_group P10-online-smoothing-train-only --wandb_tags paper-density-likelihood-rewrite,sleep,P10,online-smoothing,train-only --run_tag online_smoothing_e20_bs32_eval5 --device cuda
