#!/usr/bin/env bash
set -euo pipefail
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

# sleep transformer_4l_64h_4a density_hard seed=0
/home/ec2-user/EventDetectionPDF/.venv/bin/python train.py --dataset sleep --model transformer_4l_64h_4a --objective density_hard --datadir data/sleep --epochs 20 --folds 4 --bs 32 --downsample 10 --agg_feats stat --use_cat True --normalize True --workers 4 --seed 0 --density_prior sparse --best_metric mAP --save_all_epochs False --lr 0.003 --weight_decay 0.0 --clip_grad_norm 0.1 --tune_cutoff_steps 11 --tune_smooth_values none,1,10,100,1000 --tune_alternating True --score_after_train True --eval_every 5 --wandb True --wandb_project event-detection-pdf --wandb_log_artifacts True --tolerance_scale 1.0 --wandb_group P9-transformer-offline --wandb_mode offline --wandb_tags paper-density-likelihood-rewrite,sleep,P9,transformer-offline --run_tag transformer_offline_e20_bs32_eval5 --device cuda

# sleep transformer_4l_64h_4a seg seed=0
/home/ec2-user/EventDetectionPDF/.venv/bin/python train.py --dataset sleep --model transformer_4l_64h_4a --objective seg --datadir data/sleep --epochs 20 --folds 4 --bs 32 --downsample 10 --agg_feats stat --use_cat True --normalize True --workers 4 --seed 0 --density_prior sparse --best_metric mAP --save_all_epochs False --lr 0.003 --weight_decay 0.0 --clip_grad_norm 0.1 --tune_cutoff_steps 11 --tune_smooth_values none,1,10,100,1000 --tune_alternating True --score_after_train True --eval_every 5 --wandb True --wandb_project event-detection-pdf --wandb_log_artifacts True --tolerance_scale 1.0 --wandb_group P9-transformer-offline --wandb_mode offline --wandb_tags paper-density-likelihood-rewrite,sleep,P9,transformer-offline --run_tag transformer_offline_e20_bs32_eval5 --device cuda

# sleep transformer_4l_64h_4a density_hard seed=1
/home/ec2-user/EventDetectionPDF/.venv/bin/python train.py --dataset sleep --model transformer_4l_64h_4a --objective density_hard --datadir data/sleep --epochs 20 --folds 4 --bs 32 --downsample 10 --agg_feats stat --use_cat True --normalize True --workers 4 --seed 1 --density_prior sparse --best_metric mAP --save_all_epochs False --lr 0.003 --weight_decay 0.0 --clip_grad_norm 0.1 --tune_cutoff_steps 11 --tune_smooth_values none,1,10,100,1000 --tune_alternating True --score_after_train True --eval_every 5 --wandb True --wandb_project event-detection-pdf --wandb_log_artifacts True --tolerance_scale 1.0 --wandb_group P9-transformer-offline --wandb_mode offline --wandb_tags paper-density-likelihood-rewrite,sleep,P9,transformer-offline --run_tag transformer_offline_e20_bs32_eval5 --device cuda

# sleep transformer_4l_64h_4a seg seed=1
/home/ec2-user/EventDetectionPDF/.venv/bin/python train.py --dataset sleep --model transformer_4l_64h_4a --objective seg --datadir data/sleep --epochs 20 --folds 4 --bs 32 --downsample 10 --agg_feats stat --use_cat True --normalize True --workers 4 --seed 1 --density_prior sparse --best_metric mAP --save_all_epochs False --lr 0.003 --weight_decay 0.0 --clip_grad_norm 0.1 --tune_cutoff_steps 11 --tune_smooth_values none,1,10,100,1000 --tune_alternating True --score_after_train True --eval_every 5 --wandb True --wandb_project event-detection-pdf --wandb_log_artifacts True --tolerance_scale 1.0 --wandb_group P9-transformer-offline --wandb_mode offline --wandb_tags paper-density-likelihood-rewrite,sleep,P9,transformer-offline --run_tag transformer_offline_e20_bs32_eval5 --device cuda

# sleep transformer_4l_64h_4a density_hard seed=2
/home/ec2-user/EventDetectionPDF/.venv/bin/python train.py --dataset sleep --model transformer_4l_64h_4a --objective density_hard --datadir data/sleep --epochs 20 --folds 4 --bs 32 --downsample 10 --agg_feats stat --use_cat True --normalize True --workers 4 --seed 2 --density_prior sparse --best_metric mAP --save_all_epochs False --lr 0.003 --weight_decay 0.0 --clip_grad_norm 0.1 --tune_cutoff_steps 11 --tune_smooth_values none,1,10,100,1000 --tune_alternating True --score_after_train True --eval_every 5 --wandb True --wandb_project event-detection-pdf --wandb_log_artifacts True --tolerance_scale 1.0 --wandb_group P9-transformer-offline --wandb_mode offline --wandb_tags paper-density-likelihood-rewrite,sleep,P9,transformer-offline --run_tag transformer_offline_e20_bs32_eval5 --device cuda

# sleep transformer_4l_64h_4a seg seed=2
/home/ec2-user/EventDetectionPDF/.venv/bin/python train.py --dataset sleep --model transformer_4l_64h_4a --objective seg --datadir data/sleep --epochs 20 --folds 4 --bs 32 --downsample 10 --agg_feats stat --use_cat True --normalize True --workers 4 --seed 2 --density_prior sparse --best_metric mAP --save_all_epochs False --lr 0.003 --weight_decay 0.0 --clip_grad_norm 0.1 --tune_cutoff_steps 11 --tune_smooth_values none,1,10,100,1000 --tune_alternating True --score_after_train True --eval_every 5 --wandb True --wandb_project event-detection-pdf --wandb_log_artifacts True --tolerance_scale 1.0 --wandb_group P9-transformer-offline --wandb_mode offline --wandb_tags paper-density-likelihood-rewrite,sleep,P9,transformer-offline --run_tag transformer_offline_e20_bs32_eval5 --device cuda
